pub const INVALID_HIGH_FEE: felt252 = 'INVALID_HIGH_FEE';
pub const INVALID_HIGH_FEE_LIMIT: felt252 = 'INVALID_HIGH_FEE_LIMIT';
pub const INVALID_ZERO_ADDRESS: felt252 = 'INVALID_ZERO_ADDRESS';
pub const TOKEN_ALREADY_REGISTERED: felt252 = 'TOKEN_ALREADY_REGISTERED';
pub const TOKEN_NOT_REGISTERED: felt252 = 'TOKEN_NOT_REGISTERED';
